backend:
  name: git-gateway
  branch: master
  commit_messages:
    create: "Create {{collection}} “{{slug}}”"
    update: "Update {{collection}} “{{slug}}”"
    delete: "Delete {{collection}} “{{slug}}”"
    uploadMedia: "[skip ci] Upload “{{path}}”"
    deleteMedia: "[skip ci] Delete “{{path}}”"

local_backend: true
media_folder: static/img
public_folder: /img

collections:
  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/landing-page.md"
        label: "Landing page"
        name: "landing-page"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "landing-page",
            }
          - { label: "Wedding icon", name: "wedIcon", widget: "image" }
          - { label: "Name", name: "name", widget: "string" }
          - { label: "Date", name: "date", widget: "string"}
          - { label: "Background image", name: "bg", widget: "image"}
      - file: "src/pages/welcome-page.md"
        label: "Welcome page"
        name: "welcome-page"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "welcome-page",
            }
          - { label: "Welcome header", name: "welcomeHeader", widget: "string" }
          - { label: "Welcome sentence", name: "welcomeText", widget: "string" }
          - { label: "Background image", name: "bg", widget: "image" }
      - file: "src/pages/venue-page.md"
        label: "Venue page"
        name: "venue-page"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "venue-page",
            }
          - { label: "Header-zh_hk", name: "headerZhHK", widget: "string" }
          - { label: "Header-zh_en", name: "headerEnGB", widget: "string" }
          - { label: "Address", name: "address", widget: "string" }
          - { label: "Venue icon", name: "venueIcon", widget: "image" }
          - { label: "Venue", name: "venue", widget: "string" }
          - { label: "Restaurant", name: "restaurant", widget: "string" }
          - { label: "Background image", name: "bg", widget: "image" }
      - file: "src/pages/rundown-page.md"
        label: "Rundown Page"
        name: "rundown-page"
        fields: 
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "rundown-page",
            }
          - { label: "Header-zh_hk", name: "headerZhHK", widget: "string" }
          - { label: "Header-zh_en", name: "headerEnGB", widget: "string" }
          - label: Rundown
            name: rundown
            widget: list
            fields:
              - {label: Time, name: time, widget: string }
              - {label: Event, name: event, widget: string}
      - file: "src/pages/vaccination-page.md"
        label: "Vaccination page"
        name: "vaccination-page"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "vaccination-page",
            }
          - { label: "Vaccination icon", name: "vaccinationIcon", widget: "image" }
          - { label: "Vaccination text", name: "vaccinationText", widget: "string" }